__tests__/lib/messageUtils.test.ts, app/columns.tsx, app/page.tsx, lib/messageUtils.ts
Previously, we were linking to dashboards that didn't support the surfaces of the messages (i.e., linking to incorrect non-result dashboards).  This removes those links.
=> Bug 1880330 - only link to dashboards for supported surfaces

__tests__/lib/experimentUtils.test.ts, app/page.tsx, lib/experimentUtils.ts
Many (most? all?) live experiments have their endDate unset in the JSON.  However, we do want to display the proposed end date for live experiments. This computes that date using the startDate and the proposedDuration, and causes that to be rendered in the dashboard if the endDate is not present.
=> Bug 1880335 - used proposedDuration when needed

__tests__/app/dates.test.tsx, app/columns.tsx, app/dates.tsx, app/page.tsx
This makes the dates more readable and skimmable.  It also contains some type fixes to match the NimbusExperiment types used for dates.
=> Bug 1880564 - make Skylight exp dates skimmable

__tests__/lib/messageUtils.test.ts, app/page.tsx, lib/messageUtils.ts
This cleans up the dashboard link creation code, and adds a link to the newly created infobar dashboard (based on the messaging explore, unlike the about:welcome dashboards, which are based on the event counts explore.
It would be great to have once over on the dashboard itself as part of this review to convince ourselves that it's showing accurate stuff.
=> Bug 1880334 - Add infobar dashboards

app/columns.tsx, app/dates.tsx
This prevents the dates from wrapping in weird places, and the OffsiteLink icon from wrapping to be on a different line than the link text.
=> Prevent wrapping of dates and OffsiteLinks that looked odd, no bug

app/columns.tsx
Adds a bit of padding to the start of branch cells.
=> Bug 1883814 - clarify Skylight visual hierarchy by indenting branches

app/columns.tsx
https://bugzilla.mozilla.org/show_bug.cgi?id=1879978 is tracking fixing these and re-enabling.
=> Hide incorrectly empty dashboard link

CHANGELOG.md, __tests__/lib/messageUtils.test.ts, __tests__/lib/nimbusRecipe.test.ts, app/columns.tsx, lib/messageUtils.ts, lib/nimbusRecipe.ts
Fixed all about:welcome-based surface experiment dashboards incorrectly showing data for everything with the given message id instead of just the correct branch & experiment [bug 1887077](https://bugzilla.mozilla.org/show_bug.cgi?id=1887077).
We've now turned on dashboards for the about:welcome onboarding surface.
This issue has also (we believe) been fixed for infobar experiment dashboards as well, but we will enable those later in [bug 1890055](https://bugzilla.mozilla.org/show_bug.cgi?id=1890055) once we've had a chance to test it more.
Jointly coded and reviewed by @AllegroFox and @dmose.
=> Bug 1887077: filter on experiments & branches, enable about:welcome dashboards, temporarily disable infobar dashboards

dependabot.yml
Group the main nextjs packages group as one PR, since they're created together and are annoying to update separately.  Unfortunately, they're not scoped under @next, so we'll need to add anything from https://github.com/vercel/next.js/tree/canary/packages that's not captured by "*next*" and isn't a dep of an existing top-level package we use if we start using it.
=> Make dependabot update most nextjs packages together

.env, .env.sample, README.md, __tests__/lib/nimbusRecipeCollection.test.ts, app/page.tsx, lib/nimbusRecipeCollection.ts
Bug 1891093 - switch from pulling info from remote settings to pulling it from the Experiment API so that we can get user-friendly branch names and fix broken screenshot links.
=> Bug 1891093 - Switch from Remote Settings to Experimenter API

app/columns.tsx, lib/nimbusRecipe.ts
Bug 1891100
Changes made:
- Checks that the experiment branch's `screenshots` property is non-empty and only renders the screenshot links in that case
=> Bug 1891100 - Only render existing screenshot links

__tests__/components/ui/infoicon.test.tsx, app/page.tsx, components/ui/infobutton.tsx, components/ui/infoicon.tsx
**Bug 1891083**
Changes made:
- Updated the titles for both tables in Skylight
- Created an `InfoIcon` component using the existing tooltip components to be able to show a description of the main table when hovering over the info icon (see screenshot below)
=> Bug 1891083 - Make Skylight table titles clearer

CHANGELOG.md, __tests__/app/message-table.test.tsx, __tests__/lib/nimbusRecipe.test.ts, app/columns.tsx, app/message-table.tsx, app/page.tsx, lib/nimbusRecipe.ts
**Bug 1890870**
Changes made:
- Used the [Tanstack Table Expanding API](https://tanstack.com/table/v8/docs/guide/expanding) to make branch rows collapsible
- The chevron arrows by each experiment collapses/expands the branches to the specific experiment
- The chevron arrow at the header of the table collapses/expands all of the experiments all at once
- Currently, only toggling the chevron buttons (not the whole row) will collapse/expand
=> Bug 1890870 - Make branches collapsible for experiment tables

CHANGELOG.md, __tests__/components/ui/menubutton.test.tsx, app/page.tsx, components/ui/menubutton.tsx, components/ui/navigation-menu.tsx, package-lock.json, package.json
[**Bug 1897771**](https://bugzilla.mozilla.org/show_bug.cgi?id=1897771)
Changes made:
- Created a `menubutton.tsx` component using the [Navigation Menu shadcn component](https://ui.shadcn.com/docs/components/navigation-menu) to the top-right of Skylight which includes the following links:
- [General Info & Getting Help](https://mozilla-hub.atlassian.net/wiki/spaces/FIREFOX/pages/11043366/Onboarding+Messaging+Communication+OMC+Engineering+Team)
- [Messaging Surfaces](https://experimenter.info/messaging/desktop-messaging-surfaces/)
- [Detailed Technical Documentation](https://firefox-source-docs.mozilla.org/browser/components/newtab/content-src/asrouter/docs/)
- [Looker Top 20 Messages Dashboard](https://mozilla.cloud.looker.com/dashboards/1461?Normalized+Channel=release)
=> Bug 1897771 - First iteration of menu button for helpful messaging system info links

app/page.tsx
We never fully implemented the logout route in out Auth0, so the logout button doesn't do anything. This just removes it.
=> Remove the logout button since logout is not implemented

CHANGELOG.md, app/message-table.tsx, app/page.tsx
[**Bug 1899375**](https://bugzilla.mozilla.org/show_bug.cgi?id=1899375)
Changes made:
- Add an option to make experiment tables start fully expanded/collapsed 
- Made experiment table (not rollouts) default expanded
=> Bug 1899375 - Add default expanded option for tables

lib/nimbusRecipe.ts
[**Bug 1902424**](https://bugzilla.mozilla.org/show_bug.cgi?id=1902424)
Changes made:
- I added a fix for the weird branch ids for the following experiments: [Discovery of Search SAP Early Day EN](https://experimenter.services.mozilla.com/nimbus/discovery-of-search-sap-early-day-en/summary#treatment-b) and [Discovery of Search SAP Existing EN](https://experimenter.services.mozilla.com/nimbus/discovery-of-search-sap-existing-en/summary#treatment-b)
- Those branch ids in the jsons had `:treatment-a` at the end despite it being treatment-b branches
=> Bug 1902424 - Fix weird feature callout dashboard lossage

app/page.tsx
[**Bug 1903853**](https://bugzilla.mozilla.org/show_bug.cgi?id=1903853)
Changes made:
- Made rollout messages table fully expanded by default as per UX feedback
=> Bug 19093853 - Make rollouts table expanded by default

__tests__/app/message-table.test.tsx, __tests__/lib/looker.test.ts, __tests__/lib/messageUtils.test.ts, __tests__/lib/nimbusRecipeCollection.test.ts, app/columns.tsx, app/page.tsx, lib/looker.ts, lib/messageUtils.ts, lib/nimbusRecipeCollection.ts
[**Bug 1901036**](https://bugzilla.mozilla.org/show_bug.cgi?id=1901036)
Changes made:
- Duplicated the [infobar Looker dashboard](https://mozilla.cloud.looker.com/dashboards/1775?Messaging+System+Ping+Type=infobar&Submission+Date=30+day+ago+for+30+day&Messaging+System+Message+Id=INFOBAR_LAUNCH_ON_LOGIN_FINAL&Normalized+Channel=release&Normalized+OS=&Client+Info+App+Display+Version=&Normalized+Country+Code=&Experiment=&Experiment+Branch=) and enabled infobar CTRs in Skylight
- I noticed the CTR percents displayed in Skylight didn't accurately reflect the CTR percents in the dashboards. So the looker API query filters have been updated to match the same filters in the dashboard links, which now makes the displayed CTR percents match the ones in the dashboards. 
Note: Looker needs to be …
=> Bug 1901036 - Display more accurate CTR percents including infobar messages

__tests__/lib/messageUtils.test.ts, __tests__/lib/nimbusRecipe.test.ts, lib/messageUtils.ts, lib/nimbusRecipe.ts
[**Bug 1904388**](https://bugzilla.mozilla.org/show_bug.cgi?id=1904388)
Changes made:
- Constrained dashboard link to filter dates based on experiment `startDate` and `endDate`
- The dashboard are restricted for the following cases:
- Live message dashboards show data from the last 30 days (as it already was)
- Experiment dashboards show data from `startDate` to today (since the `endDate` properties are always null)
=> Bug 1904388 - Constrain dashboard to the experiment length

__tests__/lib/messageUtils.test.ts, __tests__/lib/nimbusRecipe.test.ts, app/columns.tsx, lib/__mocks__/sdk.ts, lib/looker.ts, lib/messageUtils.ts, lib/nimbusRecipe.ts, lib/nimbusRecipeCollection.ts
This branch is based against the current version of https://github.com/mozilla/skylight/pull/266 and will need to be merged or rebased once that lands.
So far: 
* Looker:
* Created an element for the about:welcome dashboard that shows CTR and impressions for the dashboard duration
* Forked the about:welcome dashboard
* Inserted the CTR/impression element into the forked dashboard
* Removed the "Other" line
* Clarified and corrected labels
* This branch
* Updated to use the new dashboard fork
* Added code to get the inline CTR info data from the new element
* This works for dashboards in the release section because they happen to be the 30-day length
Soo...
I think the main things left to do are:
* Make this work with the experiment dates, analogous to those changes in #266.
* handle the …
=> WIP: make inline CTR numbers cover the entire dashboard length

__tests__/lib/lookerUtils.test.ts, app/columns.tsx, lib/looker.ts, lib/messageUtils.ts
[**Bug 1905155**](https://bugzilla.mozilla.org/show_bug.cgi?id=1905155)
Changes made:
- Looker: 
- Duplicated the infobar dashboard and added a new tile to cover CTR and impressions over a duration of time (see [here](https://mozilla.cloud.looker.com/dashboards/1809?Messaging+System+Ping+Type=infobar&Submission+Date=30+days&Messaging+System+Message+Id=&Normalized+Channel=&Normalized+OS=&Client+Info+App+Display+Version=&Normalized+Country+Code=&Experiment=&Experiment+Branch=))
- Code:
- Enabled inline CTR for infobar dashboards
- Updated the dashboard ID for the new infobar dashboards
Note:
- This patch was branched off from #271 and will need to be rebased once that patch lands
=> Bug 1905155 - make inline CTR numbers cover the entire Infobar dashboard length

lib/messageUtils.ts
[**Bug 1902122**](https://bugzilla.mozilla.org/show_bug.cgi?id=1902122)
Changes made:
- Looker:
- Added "(first screen)" to the Looker dashboard title to a copy of the most recent dashboard ([here](https://mozilla.cloud.looker.com/dashboards/1818?Submission+Timestamp+Date=30+days&Message+ID=%25FAKESPOT%5E_OPTIN%5E_DEFAULT%25&Locale=&Normalized+Country+Code=&Normalized+Channel=&Version=&Metadata+User+Agent+OS=&Branch=&Experiment=))
- Code:
- Updated the dashboard ID
- Added "(1st screen)" to the `Default About:Welcome Message` surface
=> Bug 1902122 - Add "first screen" to Looker dashboard title

next.config.js
Increasing `staticPageGenerationTimeout` to 120 seconds so the build should run successfully every time. See this [PR](https://github.com/mozilla/skylight/pull/290#issuecomment-2228894675) for more context. 
rs=dmose
=> Increasing the static page generation timeout value

components/ui/menubutton.tsx, components/ui/navigation-menu.tsx
[**Bug 1898808**](https://bugzilla.mozilla.org/show_bug.cgi?id=1898808)
Changes made:
- Moved some links outside the Messaging Info menu button into the header for more visibility 
Notes:
- I'm open for suggestions on moving more/less links in/out of the Messaging Info menu button
=> Bug 1898808 - Move links outside from Messaging Info menu button

app/columns.tsx, app/page.tsx, lib/messageUtils.ts, lib/nimbusRecipe.ts, tailwind.config.ts
[**Bug 1907413**](https://bugzilla.mozilla.org/show_bug.cgi?id=1907413)
Changes made:
- Link surface tags to the appropriate docs with screenshots of the surface
- Fixed surface tags to not wrap
- Added surface tags to WNP messages
Note:
- This PR is branched off from #306 so it will need to be rebased before merging
=> Bug 1907413 - Link surface tags to experimenter.info docs

app/complete/page.tsx, app/message-table.tsx, app/page.tsx, components/ui/table.tsx
[**Bug 1909531**](https://bugzilla.mozilla.org/show_bug.cgi?id=1909531)
Changes made:
- Made the timeline component and table headers sticky
Note:
- May have to rebase if #314 gets merged first to ensure the completed page also has sticky headers
=> Bug 1909531 - Make table title and headers sticky

components/ui/menubutton.tsx, components/ui/navigation-menu.tsx
[**Bug 1909233**](https://bugzilla.mozilla.org/show_bug.cgi?id=1909233)
Changes made:
- Added a link in the header that leads to the Google Drive with all experiment briefs
Questions:
- Is the header getting too crowded? Not sure if I should move "Message Surfaces" link inside the "Messaging Info" button since surface tags will link to the same doc. 
- Is "Search briefs" informative enough?
=> Bug 1909233 - Add search experiment/rollout briefs link to header

CHANGELOG.md, components/ui/previewlinkbutton.tsx
Quick PR to make the preview button tooltips clearer; they now mention the devtools pref that needs to be set for previews to work. This is for the Mozweek demo and we can tweak it later if need be :)
=> Make preview button tooltips more clear

CHANGELOG.md, components/ui/menubutton.tsx
[Bug 1916839](https://bugzilla.mozilla.org/show_bug.cgi?id=1916839)
Changes made:
- Updated the URL for the "Search Briefs" link in the header to start a search within the experiment briefs
=> Bug 1916839 - Update URL for searching briefs

CHANGELOG.md, __tests__/ExperimentFakes.mjs, __tests__/lib/lookerUtils.test.ts, app/columns.tsx, lib/experimentUtils.ts, lib/lookerUtils.ts, lib/messageUtils.ts, lib/nimbusRecipe.ts, lib/nimbusRecipeCollection.ts
[Bug 1921080](https://bugzilla.mozilla.org/show_bug.cgi?id=1921080)
Changes made:
- Exposed dashboard links to completed rollouts and experiments
- Updated the dashboard date logic
- The new logic is now to pass in an `isCompleted` parameter to the date calculation functions, and if the message is completed, the dashboard will show data from the startDate to the endDate. Otherwise with the old logic, completed messages would always show dashboards ranging from the startDate to today.
=> Bug 1921080 - Expose dashboard links to completed messages 

__tests__/lib/nimbusRecipe.test.ts, lib/nimbusRecipe.ts
Make live Skylight instance update again by adding a bandaid so that we don't blow up on "non-msg about:welcome" feature values.  Need to talk to Meg and Jason and device something better.  No review.
=> Keep non-msg aboutwelcome features from crashing

__tests__/lib/messageUtils.test.ts, __tests__/lib/nimbusRecipe.test.ts, lib/asrouter-local-prod-messages/data.json, lib/experimentUtils.ts, lib/looker.ts, lib/messageUtils.ts, lib/nimbusRecipeCollection.ts
I found out that Looker filters can include OR statements so I tried updating logic so the message ID filters could catch the original ID, lower cased ID, and upper cased ID in all their filters for the dashboard links and CTR metrics. This would ensure that we don't always upper case all IDs and miss any message IDs that are lower case in the telemetry, without having to update anything in the dashboard LookMLs. I have this draft PR up for any initial feedback before I go in to clean up the tests.
=> Bug 1889195 - Fix lower-case message id dashboard links

__tests__/app/page.test.tsx, app/complete/page.tsx, app/page.tsx
**Description**
The `firefox` id was removed from a previous patch which caused the Firefox pill in the Timeline component to be broken. 
**Changes made:**
- Added a `firefox` id to the live message table heading and adjusted padding
=> Fix the Firefox pill in the Timeline component

__tests__/app/message-table.test.tsx, app/columns.tsx
**Changes made:**
- Truncates (and adds an ellipses) message IDs in the live message table to be max 50 characters
- Added a simple test to check that truncating occurs for long message IDs
=> Fix for long message IDs that break the UI

lib/messageUtils.ts
[Bug 1944394](https://bugzilla.mozilla.org/show_bug.cgi?id=1944394)
Changes made:
- Added a "Menu Messages" surface to recognize the surface type for `DEVICE_MIGRATION_FXA_CTA_EXP1`
=> Bug 1944394 - Update surface data to include menu messages

package-lock.json, package.json
This fixes a security issue caused by depending on a vulnerable version of the cookie package.
=> Update @auth0/nextjs-auth0 to 3.6.0

lib/messageUtils.ts
Changes made:
- Updated the infobar Looker dashboard ID to link to [the updated dashboard](https://mozilla.cloud.looker.com/dashboards/2267?Messaging+System+Ping+Type=infobar&Submission+Date=30+days&Messaging+System+Message+Id=&Normalized+Channel=&Normalized+OS=&Client+Info+App+Display+Version=&Normalized+Country+Code=&Experiment=&Experiment+Branch=)
- The primary rate calculations in the new dashboard has been updated from
```
pivot_index(${messaging_system.ping_count}, 1),
0)
/ pivot_index(${messaging_system.ping_count}, 4)
```
to
```
pivot_where(${messaging_system.metrics__string__messaging_system_event} = "CLICK_PRIMARY_BUTTON", ${messaging_system.ping_count}),
0)
/ pivot_where(${messaging_system.metrics__string__messaging_system_event} = "IMPRESSION", ${messaging_system.ping_count}) …
```
=> Bug 1957438 - Fix ctr for infobar Looker dashboards

__tests__/lib/experimentUtils.test.ts, __tests__/lib/nimbusRecipe.test.ts, app/columns.tsx, app/dashboard.tsx, lib/experimentUtils.ts, lib/messageUtils.ts, lib/nimbusRecipe.ts, lib/nimbusRecipeCollection.ts, package-lock.json, package.json
[Bug 1891121](https://bugzilla.mozilla.org/show_bug.cgi?id=1891121)
Changes made:
- `RecipeInfo` now includes an `experimentBriefLink` property with the url to experiment link Google docs
- A tooltip button of the `FileText` icon from lucide-icons is now displayed next to the experiment/rollout name if an experiment brief link exists
- The package `@mozilla/nimbus-schemas` has been imported and replaces the `NimbusExperiment` type used from `@mozilla/nimbus-shared`
=> Bug 1891121 - Add experiment brief links to experiment and rollout tables

CHANGELOG.md, __tests__/app/message-table.test.tsx, app/columns.tsx
Changes made:
- This PR adds a tooltip to the experimenter links to further differentiate them from the experimenter brief buttons, as discussed in a previous Skylight meeting
- lucide-react icon has also replaced the external link svgs
=> Add tooltip for experimenter links

CHANGELOG.md, __tests__/lib/messageUtils.test.ts, lib/messageUtils.ts
Changes made:
- Added a new tile to the android Looker dashboard https://mozilla.cloud.looker.com/dashboards/2303?Normalized%20Channel=release&Submission%20Date=30%20day&Experiment%20Slug=rootca-info-card-hcr1-fenix&Value%20Branch=&Sample%20ID=%3C%3D10&Value=info%5E_card%5E_rootCA%5E_HCR1%25
- Updated the looker dashboard ID for android so dashboard links point to the updated dashboard
=> Update Android Looker dashboard ID

.github/dependabot.yml
Right now, dependabot is not proposed major version updates to all npm packages so that we at least become aware of them.  This fixes that.
=> Add catch-all npm group, propose major updates

app/android/page.tsx
Need to correctly fix the Android dashboards as well as prevent these sorts of errors again, but since Android is currently not in use, disabling it for now to fix Desktop builds.
=> Disable Android, which was hitting limits, to make Desktop current
